[project]
name = "asyncio"
version = "0.1.0"
description = "Asyncio practice"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.2",
    "httpx>=0.28.1",
    "pillow>=12.0.0",
    "requests>=2.32.5",
]
